web_controller:
    resource: ../../src/Infrastructure/Http/Controller/Web/
    type: annotation

rest_controller:
    resource: ../../src/Infrastructure/Http/Controller/Api/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
