version: "3.3"
services:
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './apps/api/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - './apps/api/:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}
